In [1]:
# Data Transformations from Chapter 7, 8, 10, and 11 Program
# DSC 540
# Weeks 7 and 8
# Data Preparation Assignment Weeks 7 and 8
# David Berberena
# 4/28/2024

# Program Start

In [32]:
# I will import the dataset (I will be using the Candy dataset for three chapters) and display its contents here. For 
# whatever reason, the dataset was not able to be read by utf-8 encoding, so I used latin1 to read the dataset.

import pandas as pd
import numpy as np

candy = pd.read_csv('candyhierarchy2017.csv', encoding='latin1')

candy.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

## Chapter 7 Transformations

### 1. Filter Out Missing Data

In [3]:
# To filter out missing data, the dropna() function will be used. I will keep the parent dataset intact in case I need to 
# use it later on for another transformation.

candies = candy.dropna()

candies.head()

Empty DataFrame
Columns: [Internal ID, Q1: GOING OUT?, Q2: GENDER, Q3: AGE, Q4: COUNTRY, Q5: STATE, PROVINCE, COUNTY, ETC, Q6 | 100 Grand Bar, Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes), Q6 | Any full-sized candy bar, Q6 | Black Jacks, Q6 | Bonkers (the candy), Q6 | Bonkers (the board game), Q6 | Bottle Caps, Q6 | Box'o'Raisins, Q6 | Broken glow stick, Q6 | Butterfinger, Q6 | Cadbury Creme Eggs, Q6 | Candy Corn, Q6 | Candy that is clearly just the stuff given out for free at restaurants, Q6 | Caramellos, Q6 | Cash, or other forms of legal tender, Q6 | Chardonnay, Q6 | Chick-o-Sticks (we donÃ•t know what that is), Q6 | Chiclets, Q6 | Coffee Crisp, Q6 | Creepy Religious comics/Chick Tracts, Q6 | Dental paraphenalia, Q6 | Dots, Q6 | Dove Bars, Q6 | Fuzzy Peaches, Q6 | Generic Brand Acetaminophen, Q6 | Glow sticks, Q6 | Goo Goo Clusters, Q6 | Good N' Plenty, Q6 | Gum from baseball cards, Q6 | Gummy Bears straight up, Q6 | Hard Candy, Q6 | Healthy Fruit, Q6 | Heath Bar, Q6 | Hershey's Dark Chocolate, Q6 | HersheyÃ•s Milk Chocolate, Q6 | Hershey's Kisses, Q6 | Hugs (actual physical hugs), Q6 | Jolly Rancher (bad flavor), Q6 | Jolly Ranchers (good flavor), Q6 | JoyJoy (Mit Iodine!), Q6 | Junior Mints, Q6 | Senior Mints, Q6 | Kale smoothie, Q6 | Kinder Happy Hippo, Q6 | Kit Kat, Q6 | LaffyTaffy, Q6 | LemonHeads, Q6 | Licorice (not black), Q6 | Licorice (yes black), Q6 | Lindt Truffle, Q6 | Lollipops, Q6 | Mars, Q6 | Maynards, Q6 | Mike and Ike, Q6 | Milk Duds, Q6 | Milky Way, Q6 | Regular M&Ms, Q6 | Peanut M&MÃ•s, Q6 | Blue M&M's, Q6 | Red M&M's, Q6 | Green Party M&M's, Q6 | Independent M&M's, Q6 | Abstained from M&M'ing., Q6 | Minibags of chips, Q6 | Mint Kisses, Q6 | Mint Juleps, Q6 | Mr. Goodbar, Q6 | Necco Wafers, Q6 | Nerds, Q6 | Nestle Crunch, Q6 | Now'n'Laters, Q6 | Peeps, Q6 | Pencils, Q6 | Pixy Stix, Q6 | Real Housewives of Orange County Season 9 Blue-Ray, Q6 | ReeseÃ•s Peanut Butter Cups, Q6 | Reese's Pieces, Q6 | Reggie Jackson Bar, Q6 | Rolos, Q6 | Sandwich-sized bags filled with BooBerry Crunch, Q6 | Skittles, Q6 | Smarties (American), Q6 | Smarties (Commonwealth), Q6 | Snickers, Q6 | Sourpatch Kids (i.e. abominations of nature), Q6 | Spotted Dick, Q6 | Starburst, Q6 | Sweet Tarts, Q6 | Swedish Fish, Q6 | Sweetums (a friend to diabetes), Q6 | Take 5, Q6 | Tic Tacs, Q6 | Those odd marshmallow circus peanut things, Q6 | Three Musketeers, ...]
Index: []

[0 rows x 120 columns]

### 2. Fill In Missing Data

In [4]:
# It was very unexpected to see that every single column in the dataset contained missing values, so I'm glad that I kept 
# the parent dataset preserved to make more transformations on that dataset as I would have had nothing left to transform 
# had I not kept it separate. So I will simply continue to use the parent candy variable when needed.

# To fill in missing data properly, I will need to identify the columns with numerical values and those with categorical 
# values and fill them in differently. For the numerical categories, I will fill the missing values with the mean, and the 
# categorical columns will be filled with the most frequently appearing value (the mode). I can find the correct columns by 
# using the select_dtypes() functions and specifying the data types I am looking for.

# To start, I will create a variable that copies the original candy dataset and work with that new variable.

candy_filled = candy

numerical_columns = candy_filled.select_dtypes(include = ['int64', 'float64']).columns

categorical_columns = candy_filled.select_dtypes(include = ['object']).columns

# Now I will need to use fillna() twice: once to fill in the numerical columns with the mean, and once again to fill the 
# categorical columns with the mode.

candy_filled[numerical_columns] = candy_filled[numerical_columns].fillna(candy_filled[numerical_columns].mean())

# For the categorical variables, I used a for loop with the fillna() function to insert the mode using the iloc() function 
# specifying the first index.

for column in categorical_columns:
    candy_filled[column] = candy_filled[column].fillna(candy_filled[column].mode().iloc[0])

candy_filled.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,No,Male,40,USA,California,JOY,DESPAIR,JOY,DESPAIR,...,Trump,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)"
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Trump,Bottom line is Twix is really the only candy w...,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(84, 25)"
2,90272829,No,Male,49,USA,Virginia,JOY,DESPAIR,JOY,DESPAIR,...,Trump,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)"
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,Trump,Raisins can go to hell,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,Trump,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(70, 10)"

## Chapter 8 Transformations

### 1. Create Hierarchical Index

In [5]:
# To create a hierarchical index, I chose the second through fifth question columns as they looked to be the easiest to 
# have data be displayed in multiple levels. The set_index() function is what creates the hierarchical index.

hierarchical_columns = ['Q2: GENDER', 'Q3: AGE', 'Q4: COUNTRY', 'Q5: STATE, PROVINCE, COUNTY, ETC']

candy_indexed = candy_filled.set_index(hierarchical_columns)

candy_indexed.head()

                                                                 Internal ID  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                           90258773
           44      USA         NM                                   90272821
           49      USA         Virginia                             90272829
           40      us          or                                   90272840
           23      usa         exton pa                             90272841

                                                                Q1: GOING OUT?  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                   No
           44      USA         NM                                           No
           49      USA         Virginia                                     No
           40      us          or                                           No
           23      usa         exton pa                                     No

                                                                Q6 | 100 Grand Bar  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                      JOY
           44      USA         NM                                              MEH
           49      USA         Virginia                                        JOY
           40      us          or                                              MEH
           23      usa         exton pa                                        JOY

                                                                Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                                                  DESPAIR
           44      USA         NM                                                                          DESPAIR
           49      USA         Virginia                                                                    DESPAIR
           40      us          or                                                                          DESPAIR
           23      usa         exton pa                                                                    DESPAIR

                                                                Q6 | Any full-sized candy bar  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                                 JOY
           44      USA         NM                                                         JOY
           49      USA         Virginia                                                   JOY
           40      us          or                                                         JOY
           23      usa         exton pa                                                   JOY

                                                                Q6 | Black Jacks  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                DESPAIR
           44      USA         NM                                            MEH
           49      USA         Virginia                                  DESPAIR
           40      us          or                                            MEH
           23      usa         exton pa                                  DESPAIR

                                                                Q6 | Bonkers (the candy)  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                            MEH
           44      USA         NM                                                DESPAIR
           49      USA         Virginia                                              MEH
           40      us          or                                                    MEH
           23      usa         exton pa                                              MEH

                                                                Q6 | Bonkers (the board game)  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                                 MEH
           44      USA         NM                                                     DESPAIR
           49      USA         Virginia                                                   MEH
           40      us          or                                                     DESPAIR
           23      usa         exton pa                                               DESPAIR

                                                                Q6 | Bottle Caps  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                    MEH
           44      USA         NM                                        DESPAIR
           49      USA         Virginia                                      MEH
           40      us          or                                            MEH
           23      usa         exton pa                                      MEH

                                                                Q6 | Box'o'Raisins  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                  DESPAIR
           44      USA         NM                                          DESPAIR
           49      USA         Virginia                                    DESPAIR
           40      us          or                                          DESPAIR
           23      usa         exton pa                                    DESPAIR

                                                                 ...  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC  ...
Male       40      USA         California                        ...
           44      USA         NM                                ...
           49      USA         Virginia                          ...
           40      us          or                                ...
           23      usa         exton pa                          ...

                                                                Q8: DESPAIR OTHER  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                   Trump
           44      USA         NM                                           Trump
           49      USA         Virginia                                     Trump
           40      us          or                                           Trump
           23      usa         exton pa                                     Trump

                                                                                                Q9: OTHER COMMENTS  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                                             nom nom nom!
           44      USA         NM                                Bottom line is Twix is really the only candy w...
           49      USA         Virginia                                                               nom nom nom!
           40      us          or                                                           Raisins can go to hell
           23      usa         exton pa                                                               nom nom nom!

                                                                     Q10: DRESS  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                        White and gold
           44      USA         NM                                White and gold
           49      USA         Virginia                          White and gold
           40      us          or                                White and gold
           23      usa         exton pa                          White and gold

                                                                                                      Unnamed: 113  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                        dress (https://survey.ubc.ca/media/assets/user...
           44      USA         NM                                dress (https://survey.ubc.ca/media/assets/user...
           49      USA         Virginia                          dress (https://survey.ubc.ca/media/assets/user...
           40      us          or                                dress (https://survey.ubc.ca/media/assets/user...
           23      usa         exton pa                          dress (https://survey.ubc.ca/media/assets/user...

                                                                Q11: DAY  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                         Friday
           44      USA         NM                                 Sunday
           49      USA         Virginia                           Friday
           40      us          or                                 Sunday
           23      usa         exton pa                           Friday

                                                                Q12: MEDIA [Daily Dish]  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                           1.0
           44      USA         NM                                                   1.0
           49      USA         Virginia                                             1.0
           40      us          or                                                   1.0
           23      usa         exton pa                                             1.0

                                                                Q12: MEDIA [Science]  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                        1.0
           44      USA         NM                                                1.0
           49      USA         Virginia                                          1.0
           40      us          or                                                1.0
           23      usa         exton pa                                          1.0

                                                                Q12: MEDIA [ESPN]  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                     1.0
           44      USA         NM                                             1.0
           49      USA         Virginia                                       1.0
           40      us          or                                             1.0
           23      usa         exton pa                                       1.0

                                                                Q12: MEDIA [Yahoo]  \
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                      1.0
           44      USA         NM                                              1.0
           49      USA         Virginia                                        1.0
           40      us          or                                              1.0
           23      usa         exton pa                                        1.0

                                                                Click Coordinates (x, y)
Q2: GENDER Q3: AGE Q4: COUNTRY Q5: STATE, PROVINCE, COUNTY, ETC
Male       40      USA         California                                       (77, 24)
           44      USA         NM                                               (84, 25)
           49      USA         Virginia                                         (77, 24)
           40      us          or                                               (75, 23)
           23      usa         exton pa                                         (70, 10)

[5 rows x 116 columns]

### 2. Reshape

In [8]:
# To reshape the data, I took the same candy_filled dataset that has been hierarchically indexed and used the stack() 
# function on it. 

stacked_reshaped_candy = candy_indexed.stack()

stacked_reshaped_candy.head()

Q2: GENDER  Q3: AGE  Q4: COUNTRY  Q5: STATE, PROVINCE, COUNTY, ETC
Male        40       USA          California                        Internal ID                                                                               90258773
                                                                    Q1: GOING OUT?                                                                                  No
                                                                    Q6 | 100 Grand Bar                                                                             JOY
                                                                    Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)     DESPAIR
                                                                    Q6 | Any full-sized candy bar                                                                  JOY
dtype: object

## Chapter 10 Transformations

### 1. Grouping with Index Levels

In [20]:
# Grouping is done with the groupby() function, and to group the hierarchically indexed dataset made in the Chapter 8 
# transformations, I can specify the index level as an argument of groupby(). I chose the first index for convenience 
# (although I did see the other three levels and some of the observations were funny). The book used the count() function 
# also, which I included as well to show the number of observations were in the first index level.

grouped_index_candy = candy_indexed.groupby(level = 0).count()

grouped_index_candy

,Internal ID,Q1: GOING OUT?,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,Q6 | Box'o'Raisins,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Q2: GENDER,,,,,,,,,,,,,,,,,,,,,
Female,839,839,839,839,839,839,839,839,839,839,...,839,839,839,839,839,839,839,839,839,839
I'd rather not say,83,83,83,83,83,83,83,83,83,83,...,83,83,83,83,83,83,83,83,83,83
Male,1508,1508,1508,1508,1508,1508,1508,1508,1508,1508,...,1508,1508,1508,1508,1508,1508,1508,1508,1508,1508
Other,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30

### 2. Split/Apply/Combine

In [30]:
# To perform a split/apply/combine on the data, I will take my already grouped data and apply a function to it with the 
# apply() function. I chose to make a basic sum function to show that when the function is applied to the dataset, the 
# answer across all columns should be the total number of entries. 

def add_it_up(groups):
    return groups.sum()

applied_candy = grouped_index_candy.apply(add_it_up)

applied_candy

Internal ID                                                                               2460
Q1: GOING OUT?                                                                            2460
Q6 | 100 Grand Bar                                                                        2460
Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)    2460
Q6 | Any full-sized candy bar                                                             2460
                                                                                          ...
Q12: MEDIA [Daily Dish]                                                                   2460
Q12: MEDIA [Science]                                                                      2460
Q12: MEDIA [ESPN]                                                                         2460
Q12: MEDIA [Yahoo]                                                                        2460
Click Coordinates (x, y)                                                                  2460
Length: 116, dtype: int64

## Chapter 11 Transformations

### 1. Converting Between String and Datetime

In [53]:
# For this transformation, I need to add a new column to the dataframe containing data that can be converted between string 
# and datetime formats. I will be using the candy_filled variable for ease of reading the dataset. The pd.to_datetime() 
# function is used to convert the string '2020-02-02' to a datetime format in Python. 

# After running the below code, I received a PerformanceWarning that the data was very fragmented. I included and imported 
# the warnings code and module to ignore all warnings so it would not show in the code output.

import warnings

warnings.filterwarnings("ignore")

candy_filled['Date_of_data'] = pd.to_datetime('2020-02-02')

candy_filled.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_of_data
0,90258773,No,Male,40,USA,California,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-02-02
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Bottom line is Twix is really the only candy w...,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(84, 25)",2020-02-02
2,90272829,No,Male,49,USA,Virginia,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-02-02
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,Raisins can go to hell,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(75, 23)",2020-02-02
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(70, 10)",2020-02-02

In [54]:
# Here, I will convert the newly created datetime column data into string format data using the strftime() function.

candy_filled['Date_of_data'] = candy_filled['Date_of_data'].dt.strftime('%Y-%M-%D')

candy_filled.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_of_data
0,90258773,No,Male,40,USA,California,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-00-02/02/20
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Bottom line is Twix is really the only candy w...,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(84, 25)",2020-00-02/02/20
2,90272829,No,Male,49,USA,Virginia,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-00-02/02/20
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,Raisins can go to hell,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(75, 23)",2020-00-02/02/20
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(70, 10)",2020-00-02/02/20

### 2. Generate Date Range

In [57]:
# Now that I have a datetime column (which has now been converted back to string format), I will convert the column back to 
# datetime format, then use the pd.date_range() function to specify a range of dates matching the number of rows within the 
# dataset using the start and periods arguments within the function. 

candy_filled['Date_of_data'] = pd.to_datetime('2020-02-02')

number_of_dates = len(candy_filled)

range_of_dates = pd.date_range(start = '2020-02-02', periods = number_of_dates)

candy_filled['Date_of_data'] = range_of_dates

candy_filled.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_of_data
0,90258773,No,Male,40,USA,California,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-02-02
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Bottom line is Twix is really the only candy w...,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(84, 25)",2020-02-03
2,90272829,No,Male,49,USA,Virginia,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(77, 24)",2020-02-04
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,Raisins can go to hell,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Sunday,1.0,1.0,1.0,1.0,"(75, 23)",2020-02-05
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,nom nom nom!,White and gold,dress (https://survey.ubc.ca/media/assets/user...,Friday,1.0,1.0,1.0,1.0,"(70, 10)",2020-02-06